"""
circuit-backend/main.py
========================
Single-route FastAPI server that accepts a resistive-circuit netlist,
writes a SPICE deck, runs it through ngspice (batch/console mode), parses
the output, and returns branch currents (in Amperes).

Run:
    uvicorn main:app --reload --port 8000

Prerequisites:
    pip install fastapi uvicorn
    ngspice must be on PATH.
    On Windows (Chocolatey install) the console binary is ngspice_con.exe —
    this is detected automatically. You can also set NGSPICE_PATH env var.
"""

import json
import os
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(title="Circuit Simulator Backend")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

class NetlistComponent(BaseModel):
    id: str
    ref: str
    type: str
    nodes: list[str]
    params: dict[str, float]

class Netlist(BaseModel):
    version: int
    components: list[NetlistComponent]
    nets: list[str]

class TransientConfig(BaseModel):
    stepSeconds: float
    stopSeconds: float

class AcConfig(BaseModel):
    startHz: float
    stopHz: float
    pointsPerDecade: int

class Analysis(BaseModel):
    mode: str
    tran: TransientConfig | None = None
    ac: AcConfig | None = None

class SimulateRequest(BaseModel):
    netlist: Netlist
    analysis: Analysis

class BranchInfo(BaseModel):
    component_id: str
    ref: str
    type: str
    node_a: str
    node_b: str
    voltage_a: float
    voltage_b: float
    delta_v: float
    current_a: float
    direction: str

class SimulationResult(BaseModel):
    ok: bool
    message: str | None = None
    traces: dict[str, list[float]] | None = None
    branch_analysis: list[BranchInfo] | None = None

_TYPE_TO_SPICE = {
    "resistor":   "R",
    "capacitor":  "C",
    "inductor":   "L",
    "vsource_dc": "V",
    "vsource_ac": "V",
    "battery":    "V",
    "vsource_dep": "V",
    "diode":      "D",
    "ground":     None,
}
_VOLTAGE_SOURCES = {"vsource_dc", "vsource_ac", "battery", "vsource_dep"}

class _Deck:
    """A SPICE deck plus the names needed to read each component's result.

    Every element gets an index-based SPICE name (V0_V1, R2_R1, ...), so two
    parts that share a ref - the DC and AC source palettes both number from
    V1 - can't clash. Each passive part also gets a 0 V sense source in
    series, so ngspice reports the true current through it (capacitors and
    inductors included) as `<sense>#branch`, positive from pin A to pin B."""
    def __init__(self) -> None:
        self.text = ""
        # component index -> (branch vector name, is_voltage_source)
        self.branch: dict[int, tuple[str, bool]] = {}
        self.nodes: list[str] = []
        self.ac_freq: float | None = None

    def vectors(self) -> list[str]:
        return [f"v({n})" for n in self.nodes] + [f"{br}#branch" for br, _ in self.branch.values()]


def _spice_name(prefix: str, idx: int, ref: str) -> str:
    return f"{prefix}{idx}_{re.sub(r'[^A-Za-z0-9]', '', ref) or 'X'}"


def _build_spice_deck(netlist: Netlist, ac_freq: float | None) -> _Deck:
    """Build the deck. With `ac_freq`, a single-frequency AC analysis at that
    frequency gives the sinusoidal steady state; otherwise the DC operating
    point is solved."""
    # Any net touching a GND component is SPICE's reference node "0".
    gnd_nets: set[str] = set()
    for comp in netlist.components:
        if comp.type == "ground":
            gnd_nets.update(comp.nodes)

    def _node(n: str) -> str:
        return "0" if n in gnd_nets else n

    deck = _Deck()
    deck.ac_freq = ac_freq
    lines: list[str] = ["* Auto-generated by circuit-backend"]
    nodes: set[str] = set()
    uses_diode = False
    for idx, comp in enumerate(netlist.components):
        prefix = _TYPE_TO_SPICE.get(comp.type)
        if prefix is None or len(comp.nodes) < 2:
            continue
        a, b = _node(comp.nodes[0]), _node(comp.nodes[1])
        nodes.update((a, b))
        name = _spice_name(prefix, idx, comp.ref)
        p = comp.params
        if comp.type in _VOLTAGE_SOURCES:
            if comp.type == "vsource_ac":
                # The editor stores the AC source's peak as "amplitude".
                v = p.get("amplitude", p.get("voltage", 1))
                freq = p.get("frequency", 50)
                lines.append(f"{name} {a} {b} DC 0 AC {v} SIN(0 {v} {freq})")
            else:
                lines.append(f"{name} {a} {b} DC {p.get('voltage', 5)}")
            deck.branch[idx] = (name.lower(), True)
            continue
        sense_node = f"s{idx}"
        sense = f"VS{idx}"
        if comp.type == "resistor":
            lines.append(f"{name} {a} {sense_node} {p.get('resistance', 1000) or 1000}")
        elif comp.type == "capacitor":
            lines.append(f"{name} {a} {sense_node} {p.get('capacitance', 1e-6)}")
        elif comp.type == "inductor":
            lines.append(f"{name} {a} {sense_node} {p.get('inductance', 1e-3)}")
        elif comp.type == "diode":
            lines.append(f"{name} {a} {sense_node} DMOD")
            uses_diode = True
        lines.append(f"{sense} {sense_node} {b} 0")
        deck.branch[idx] = (sense.lower(), False)
    if uses_diode:
        lines.append(".model DMOD D(IS=2.52n RS=0.568 N=1.752)")

    deck.nodes = sorted(n for n in nodes if n != "0")
    vectors = deck.vectors()
    lines.append(".control")
    if ac_freq is None:
        lines.append("op")
        cmd = " ".join(vectors)
    else:
        lines.append(f"ac lin 1 {ac_freq} {ac_freq}")
        cmd = " ".join(f"real({v}) imag({v})" for v in vectors)
    lines.append("echo RESULTS_BEGIN")
    if cmd:
        lines.append(f"print {cmd}")
    lines.append("echo RESULTS_END")
    lines.append(".endc")
    lines.append(".end")
    deck.text = "\n".join(lines)
    return deck

def _find_ngspice() -> str:
    """Return the path to the ngspice console/batch binary.

    Priority:
      1. NGSPICE_PATH environment variable (explicit override)
      2. ngspice_con  – Windows Chocolatey installs the headless binary here
      3. ngspice      – standard PATH name on Linux/macOS and some Windows builds
    """
    env_path = os.environ.get("NGSPICE_PATH")
    if env_path:
        return env_path
    # On Windows, prefer the console (non-GUI) variant installed by Chocolatey
    if os.name == "nt":
        for candidate in ("ngspice_con", "ngspice"):
            try:
                result = subprocess.run(
                    [candidate, "-v"],
                    capture_output=True, timeout=5,
                )
                return candidate          # found and runnable
            except FileNotFoundError:
                continue
    return "ngspice"

NGSPICE = _find_ngspice()
print(f"[circuit-backend] Using ngspice binary: {NGSPICE!r}")

def _run_ngspice(spice_deck: str) -> str:
    with tempfile.NamedTemporaryFile(mode="w", suffix=".cir", delete=False, encoding="utf-8") as f:
        f.write(spice_deck)
        cir_path = f.name
    try:
        result = subprocess.run(
            [NGSPICE, "-b", cir_path],
            capture_output=True, text=True, timeout=30,
        )
        return result.stdout + result.stderr
    finally:
        Path(cir_path).unlink(missing_ok=True)

# `print` of single-point vectors gives one `name = value` line per vector.
_PRINT_LINE_RE = re.compile(
    r"^\s*([^\s=]+)\s*=\s*([-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?)\s*$",
    re.MULTILINE,
)

def _parse_results(raw: str, deck: _Deck) -> dict[str, complex] | None:
    """Vector name (lower-case, e.g. 'v(1)', 'vs3#branch') -> value. DC values
    come back as real numbers, AC values as complex phasors. None when
    ngspice didn't produce every value (e.g. a singular circuit)."""
    start = raw.find("RESULTS_BEGIN")
    end = raw.find("RESULTS_END", start)
    if start < 0 or end < 0:
        return None
    printed = {m.group(1).lower(): float(m.group(2))
               for m in _PRINT_LINE_RE.finditer(raw[start:end])}
    values: dict[str, complex] = {}
    for v in deck.vectors():
        if deck.ac_freq is None:
            if v not in printed:
                return None
            values[v] = complex(printed[v], 0.0)
        else:
            re_v, im_v = printed.get(f"real({v})"), printed.get(f"imag({v})")
            if re_v is None or im_v is None:
                return None
            values[v] = complex(re_v, im_v)
    return values


def _signed(z: complex) -> float:
    """Collapse a phasor to one signed number for display: its magnitude,
    signed by the in-phase (real) part relative to the source - or by the
    quadrature part when it is almost purely reactive. DC values pass through."""
    mag = abs(z)
    if mag == 0:
        return 0.0
    ref = z.real if abs(z.real) > 1e-6 * mag else z.imag
    return mag if ref >= 0 else -mag


def _compute_branch_analysis(netlist: Netlist, deck: _Deck, values: dict[str, complex]) -> list[dict]:
    """
    Per-component branch analysis using standard EE conventions:

    1. Node voltages are relative to ground (node "0" = 0 V).
    2. Small numerical noise near zero is clamped to 0 V.
    3. Passive sign convention: delta_v = V(node_a) - V(node_b); current is
       the true current through the part (from its series sense source),
       positive when it flows a->b.
    4. Voltage sources: ngspice's v#branch is the current INTO the positive
       terminal. It is negated to give the conventional current that EXITS
       the positive terminal into the circuit.
    5. AC (sinusoidal steady state): voltages and currents are peak
       amplitudes; the sign gives the direction relative to the source phase.
    """
    _ZERO_SNAP = 1e-3  # 1 mV: any |V| below this is snapped to 0 V
    _CURRENT_SNAP = 1e-9  # 1 nA: any |I| below this is snapped to 0 A
    gnd_nets = {n for c in netlist.components if c.type == "ground" for n in c.nodes}

    def phasor(node: str) -> complex:
        return 0j if node == "0" or node in gnd_nets else values.get(f"v({node})", 0j)

    def volts(z: complex) -> float:
        # Node potentials: DC keeps its sign; AC shows the amplitude.
        v = z.real if deck.ac_freq is None else abs(z)
        return 0.0 if abs(v) < _ZERO_SNAP else round(v, 6)

    branches: list[dict] = []
    for idx, comp in enumerate(netlist.components):
        if idx not in deck.branch:
            continue
        na, nb = comp.nodes[0].lower(), comp.nodes[1].lower()
        za, zb = phasor(comp.nodes[0]), phasor(comp.nodes[1])
        dv = _signed(za - zb)
        if abs(dv) < _ZERO_SNAP:
            dv = 0.0
        br, is_source = deck.branch[idx]
        i = values.get(f"{br}#branch", 0j)
        current = _signed(-i if is_source else i)
        # ngspice's GMIN leakage (~1e-12 S per node) shows up as pA "currents"
        # in branches that really carry none (e.g. behind a capacitor at DC).
        if abs(current) < _CURRENT_SNAP:
            current, direction = 0.0, "none"
        else:
            direction = "a_to_b" if current > 0 else "b_to_a"
        branches.append({
            "component_id": comp.id,
            "ref": comp.ref,
            "type": comp.type,
            "node_a": na,
            "node_b": nb,
            "voltage_a": volts(za),
            "voltage_b": volts(zb),
            "delta_v": round(dv, 6),
            "current_a": round(current, 12),
            "direction": direction,
        })
    print("=== Branch analysis ===")
    for b in branches:
        arrow = "a->b" if b["direction"] == "a_to_b" else ("b->a" if b["direction"] == "b_to_a" else " 0 ")
        print(f"  {b['ref']:5s} ({b['type']:12s})  Va={b['voltage_a']:+.3f}V  Vb={b['voltage_b']:+.3f}V  dV={b['delta_v']:+.4f}V  I={b['current_a']:+.6e}A  [{arrow}]")
    print("=======================\n")
    return branches

@app.post("/simulate", response_model=SimulationResult)
async def simulate(req: SimulateRequest) -> Any:
    # A circuit driven by an AC source has no meaningful DC operating point
    # (the source is 0 V at DC), so solve its sinusoidal steady state at the
    # source frequency instead - unless DC analysis was asked for explicitly.
    ac_sources = [c for c in req.netlist.components if c.type == "vsource_ac"]
    ac_freq: float | None = None
    if ac_sources and req.analysis.mode != "dc":
        ac_freq = float(ac_sources[0].params.get("frequency", 50)) or 50.0

    deck = _build_spice_deck(req.netlist, ac_freq)
    print("\n=== SPICE deck ===")
    print(deck.text)
    print("==================\n")
    try:
        raw_output = _run_ngspice(deck.text)
    except FileNotFoundError:
        raise HTTPException(status_code=500, detail=f"ngspice not found at '{NGSPICE}'. Install ngspice and make sure it is on your PATH, or set the NGSPICE_PATH environment variable.")
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=500, detail="ngspice timed out.")
    print("=== ngspice raw output ===")
    print(raw_output)
    print("==========================\n")
    values = _parse_results(raw_output, deck)
    if values is None:
        errors = [ln.strip() for ln in raw_output.splitlines() if "error" in ln.lower()]
        detail = "\n".join(errors[:5]) or raw_output[-1500:]
        return SimulationResult(ok=False, message=f"ngspice could not solve this circuit.\n\n{detail}")

    traces: dict[str, list[float]] = {}
    for n in deck.nodes:
        traces[f"V({n.upper()})"] = [_signed(values[f"v({n})"])]
    for idx, (br, _) in deck.branch.items():
        traces[f"I({req.netlist.components[idx].ref.upper()})"] = [_signed(values[f"{br}#branch"])]
    branch_analysis = _compute_branch_analysis(req.netlist, deck, values)

    message = None
    if ac_freq is not None:
        message = f"✓ AC steady state at {ac_freq:g} Hz — values are peak amplitudes"
        if len({c.params.get("frequency", 50) for c in ac_sources}) > 1:
            message += f" (all AC sources solved at {ac_freq:g} Hz)"
        if any(c.type in _VOLTAGE_SOURCES - {"vsource_ac"} for c in req.netlist.components):
            message += "; DC sources are not included"
    return SimulationResult(ok=True, message=message, traces=traces,
                            branch_analysis=[BranchInfo(**b) for b in branch_analysis])

class GenerateCircuitRequest(BaseModel):
    image: str
    title: str = "drawn-circuit"
    # Boxes already found by /detect-components on this exact image (RTP).
    # When given, /generate-circuit reuses them instead of re-running YOLO.
    detections: list[dict[str, Any]] | None = None

def _decode_request_image(req: GenerateCircuitRequest):
    import base64
    import binascii
    from recognizer import decode_image
    payload = req.image.split(",", 1)[1] if req.image.startswith("data:") else req.image
    try:
        data = base64.b64decode(payload, validate=True)
    except binascii.Error:
        raise HTTPException(status_code=400, detail="Image is not valid base64.")
    return decode_image(data)

@app.post("/detect-components")
def detect_components(req: GenerateCircuitRequest) -> dict[str, Any]:
    from recognizer import RecognitionError, box_to_json, detect_boxes
    image = _decode_request_image(req)
    try:
        boxes = detect_boxes(image)
    except RecognitionError as e:
        raise HTTPException(status_code=422, detail=str(e))
    h, w = image.shape[:2]
    return {
        "image_width": w, "image_height": h,
        "detections": [box_to_json(b) for b in boxes],
    }

@app.post("/generate-circuit")
def generate_circuit(req: GenerateCircuitRequest) -> dict[str, Any]:
    from recognizer import RecognitionError, box_from_json, recognize
    image = _decode_request_image(req)
    boxes = None
    if req.detections is not None:
        try:
            boxes = [box_from_json(d) for d in req.detections]
        except (KeyError, TypeError, ValueError):
            raise HTTPException(status_code=400, detail="Malformed detections.")
    try:
        return recognize(image, title=req.title, boxes=boxes)
    except RecognitionError as e:
        raise HTTPException(status_code=422, detail=str(e))

@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}