"""
circuit-backend/main.py
========================
Single-route FastAPI server that accepts a resistive-circuit netlist,
writes a SPICE deck, runs it through ngspice (batch/console mode), parses
the output, and returns branch currents (in Amperes).

Run:
    uvicorn main:app --reload --port 8000

Prerequisites:
    pip install fastapi uvicorn
    ngspice must be on PATH.
    On Windows (Chocolatey install) the console binary is ngspice_con.exe —
    this is detected automatically. You can also set NGSPICE_PATH env var.
"""

import json
import os
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(title="Circuit Simulator Backend")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

class NetlistComponent(BaseModel):
    id: str
    ref: str
    type: str
    nodes: list[str]
    params: dict[str, float]

class Netlist(BaseModel):
    version: int
    components: list[NetlistComponent]
    nets: list[str]

class TransientConfig(BaseModel):
    stepSeconds: float
    stopSeconds: float

class AcConfig(BaseModel):
    startHz: float
    stopHz: float
    pointsPerDecade: int

class Analysis(BaseModel):
    mode: str
    tran: TransientConfig | None = None
    ac: AcConfig | None = None

class SimulateRequest(BaseModel):
    netlist: Netlist
    analysis: Analysis

class BranchInfo(BaseModel):
    component_id: str
    ref: str
    type: str
    node_a: str
    node_b: str
    voltage_a: float
    voltage_b: float
    delta_v: float
    current_a: float
    direction: str

class SimulationResult(BaseModel):
    ok: bool
    message: str | None = None
    traces: dict[str, list[float]] | None = None
    branch_analysis: list[BranchInfo] | None = None

_TYPE_TO_SPICE = {
    "resistor":   "R",
    "capacitor":  "C",
    "inductor":   "L",
    "vsource_dc": "V",
    "vsource_ac": "V",
    "battery":    "V",
    "vsource_dep": "V",
    "diode":      "D",
    "ground":     None,
}

def _build_spice_deck(netlist: Netlist) -> str:
    # ── Step 1: find which nets are connected to GND components.
    #            SPICE requires the reference node to be named "0".
    gnd_nets: set[str] = set()
    for comp in netlist.components:
        if comp.type == "ground":
            for n in comp.nodes:
                gnd_nets.add(n)

    def _node(n: str) -> str:
        """Rename any GND-connected net to SPICE node '0'."""
        return "0" if n in gnd_nets else n

    lines: list[str] = ["* Auto-generated by circuit-backend"]
    voltage_sources: list[str] = []
    uses_diode = False
    for comp in netlist.components:
        prefix = _TYPE_TO_SPICE.get(comp.type)
        if prefix is None:
            continue
        nodes = " ".join(_node(n) for n in comp.nodes)
        if comp.type == "resistor":
            r = comp.params.get("resistance", 1000)
            lines.append(f"R{comp.ref.lstrip('R')} {nodes} {r}")
        elif comp.type == "capacitor":
            c = comp.params.get("capacitance", 1e-6)
            lines.append(f"C{comp.ref.lstrip('C')} {nodes} {c}")
        elif comp.type == "inductor":
            l = comp.params.get("inductance", 1e-3)
            lines.append(f"L{comp.ref.lstrip('L')} {nodes} {l}")
        elif comp.type == "vsource_dc":
            v = comp.params.get("voltage", 5)
            lines.append(f"V{comp.ref.lstrip('V')} {nodes} DC {v}")
            voltage_sources.append(comp.ref)
        elif comp.type in ("battery", "vsource_dep"):
            v = comp.params.get("voltage", 5)
            name = comp.ref if comp.ref.startswith("V") else f"V{comp.ref}"
            lines.append(f"{name} {nodes} DC {v}")
            voltage_sources.append(name)
        elif comp.type == "diode":
            lines.append(f"D{comp.ref.lstrip('D')} {nodes} DMOD")
            uses_diode = True
        elif comp.type == "vsource_ac":
            v = comp.params.get("voltage", 1)
            freq = comp.params.get("frequency", 50)
            lines.append(f"V{comp.ref.lstrip('V')} {nodes} AC {v} SIN(0 {v} {freq})")
            voltage_sources.append(comp.ref)
    if uses_diode:
        lines.append(".model DMOD D(IS=2.52n RS=0.568 N=1.752)")
    lines.append(".op")
    lines.append(".end")
    return "\n".join(lines)

def _find_ngspice() -> str:
    """Return the path to the ngspice console/batch binary.

    Priority:
      1. NGSPICE_PATH environment variable (explicit override)
      2. ngspice_con  – Windows Chocolatey installs the headless binary here
      3. ngspice      – standard PATH name on Linux/macOS and some Windows builds
    """
    env_path = os.environ.get("NGSPICE_PATH")
    if env_path:
        return env_path
    # On Windows, prefer the console (non-GUI) variant installed by Chocolatey
    if os.name == "nt":
        for candidate in ("ngspice_con", "ngspice"):
            try:
                result = subprocess.run(
                    [candidate, "-v"],
                    capture_output=True, timeout=5,
                )
                return candidate          # found and runnable
            except FileNotFoundError:
                continue
    return "ngspice"

NGSPICE = _find_ngspice()
print(f"[circuit-backend] Using ngspice binary: {NGSPICE!r}")

def _run_ngspice(spice_deck: str) -> str:
    with tempfile.NamedTemporaryFile(mode="w", suffix=".cir", delete=False, encoding="utf-8") as f:
        f.write(spice_deck)
        cir_path = f.name
    try:
        result = subprocess.run(
            [NGSPICE, "-b", cir_path],
            capture_output=True, text=True, timeout=30,
        )
        return result.stdout + result.stderr
    finally:
        Path(cir_path).unlink(missing_ok=True)

# ngspice-47 output format:
#   Node voltages:    V(1)           5.005000e+00
#   Branch currents:  v1#branch      -5.00000e-03
# (values are whitespace-separated from the label, no '=' sign)
_NODE_VOLTAGE_RE = re.compile(
    r"v\((\w+)\)\s+([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
    re.IGNORECASE,
)
_BRANCH_CURRENT_RE = re.compile(
    r"(\w+)#branch\s+([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
    re.IGNORECASE,
)
# Legacy fallback for simulators that use 'i(vX) = value' format
_CURRENT_RE_LEGACY = re.compile(
    r"i\(v(\w+)\)\s*=\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
    re.IGNORECASE,
)
_NODE_VOLTAGE_RE_LEGACY = re.compile(
    r"v\((\w+)\)\s*=\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
    re.IGNORECASE,
)

def _parse_op_output(raw: str) -> dict[str, float]:
    results: dict[str, float] = {}
    # Node voltages (ngspice-47 format: 'V(1)    5.005e+00')
    for m in _NODE_VOLTAGE_RE.finditer(raw):
        results[f"V({m.group(1).upper()})"] = float(m.group(2))
    # Branch currents (ngspice-47 format: 'v1#branch   -5e-03')
    for m in _BRANCH_CURRENT_RE.finditer(raw):
        vsrc = m.group(1).upper()          # e.g. "V1"
        results[f"I({vsrc})"] = float(m.group(2))
    # Legacy fallback ('i(vX) = value', 'v(X) = value')
    if not results:
        for m in _CURRENT_RE_LEGACY.finditer(raw):
            results[f"I(V{m.group(1).upper()})"] = float(m.group(2))
        for m in _NODE_VOLTAGE_RE_LEGACY.finditer(raw):
            results[f"V({m.group(1).upper()})"] = float(m.group(2))
    return results

def _compute_branch_analysis(netlist: Netlist, op_values: dict[str, float]) -> list[dict]:
    """
    Compute per-component branch analysis using standard EE conventions:

    1. Node voltages are relative to explicit ground (node "0" = 0 V).
    2. Small numerical noise near zero is clamped to 0 V.
    3. Passive Sign Convention: delta_v = V(node_a) - V(node_b) and
       current is reported as a POSITIVE magnitude; direction arrow shows
       actual flow (a→b when delta_v > 0 for passive components).
    4. Voltage-source current from ngspice (v#branch) is the current INTO
       the positive terminal. We negate it to get the conventional current
       that EXITS the positive terminal (which is the physically meaningful
       quantity students expect to see flowing around the loop).
    """
    _ZERO_SNAP = 1e-3  # 1 mV threshold: any |V| < 1mV is strictly snapped to 0.0 V

    node_voltage: dict[str, float] = {}
    for label, val in op_values.items():
        if label.startswith("V("):
            raw_node = label[2:-1].lower()
            # Snap near-zero node voltages to exactly 0 V
            node_voltage[raw_node] = 0.0 if abs(val) < _ZERO_SNAP else val
    node_voltage["0"] = 0.0

    branches: list[dict] = []
    for comp in netlist.components:
        if len(comp.nodes) < 2:
            continue
        na = comp.nodes[0].lower()
        nb = comp.nodes[1].lower()
        va = 0.0 if na == "0" or abs(node_voltage.get(na, 0.0)) < _ZERO_SNAP else node_voltage.get(na, 0.0)
        vb = 0.0 if nb == "0" or abs(node_voltage.get(nb, 0.0)) < _ZERO_SNAP else node_voltage.get(nb, 0.0)
        dv = va - vb  # Passive sign convention: V_a − V_b
        if abs(dv) < _ZERO_SNAP:
            dv = 0.0

        if comp.type == "resistor":
            r = comp.params.get("resistance", 1000) or 1000
            # Passive sign convention: I = ΔV / R, positive means a→b
            current = dv / r
        elif comp.type == "capacitor":
            current = 0.0
        elif comp.type in ("vsource_dc", "battery", "vsource_dep", "vsource_ac"):
            ru = comp.ref.upper()
            vref = ru if ru.startswith("V") else f"V{ru}"
            # ngspice v#branch = current INTO positive terminal.
            # Negate → conventional current EXITING positive terminal.
            raw_i = op_values.get(f"I({vref})", 0.0)
            current = -raw_i  # positive = flowing out of + terminal into the circuit
        else:
            current = dv  # fallback

        # Direction follows actual current sign (passive sign convention)
        if abs(current) < 1e-15:
            direction = "none"
        elif current > 0:
            direction = "a_to_b"
        else:
            direction = "b_to_a"

        branches.append({
            "component_id": comp.id,
            "ref": comp.ref,
            "type": comp.type,
            "node_a": na,
            "node_b": nb,
            "voltage_a": 0.0 if abs(va) < _ZERO_SNAP else round(va, 6),
            "voltage_b": 0.0 if abs(vb) < _ZERO_SNAP else round(vb, 6),
            "delta_v": 0.0 if abs(dv) < _ZERO_SNAP else round(dv, 6),
            "current_a": round(current, 9),
            "direction": direction,
        })
    print("=== Branch analysis ===")
    for b in branches:
        arrow = "a->b" if b["direction"] == "a_to_b" else ("b->a" if b["direction"] == "b_to_a" else " 0 ")
        print(f"  {b['ref']:5s} ({b['type']:12s})  Va={b['voltage_a']:+.3f}V  Vb={b['voltage_b']:+.3f}V  dV={b['delta_v']:+.4f}V  I={b['current_a']:+.6e}A  [{arrow}]")
    print("=======================\n")
    return branches

@app.post("/simulate", response_model=SimulationResult)
async def simulate(req: SimulateRequest) -> Any:
    spice = _build_spice_deck(req.netlist)
    print("\n=== SPICE deck ===")
    print(spice)
    print("==================\n")
    try:
        raw_output = _run_ngspice(spice)
    except FileNotFoundError:
        raise HTTPException(status_code=500, detail=f"ngspice not found at '{NGSPICE}'. Install ngspice and make sure it is on your PATH, or set the NGSPICE_PATH environment variable.")
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=500, detail="ngspice timed out.")
    print("=== ngspice raw output ===")
    print(raw_output)
    print("==========================\n")
    op_values = _parse_op_output(raw_output)
    if not op_values:
        return SimulationResult(ok=False, message=f"ngspice ran but no values were parsed.\n\nRaw output:\n{raw_output}")
    print("=== Branch currents (Amperes) ===")
    for label, value in op_values.items():
        if label.startswith("I("):
            print(f"  {label} = {value:.6e} A")
    print("=================================\n")
    traces: dict[str, list[float]] = {k: [v] for k, v in op_values.items()}
    branch_analysis = _compute_branch_analysis(req.netlist, op_values)
    return SimulationResult(ok=True, traces=traces, branch_analysis=[BranchInfo(**b) for b in branch_analysis])

class GenerateCircuitRequest(BaseModel):
    image: str
    title: str = "drawn-circuit"

def _decode_request_image(req: GenerateCircuitRequest):
    import base64
    import binascii
    from recognizer import decode_image
    payload = req.image.split(",", 1)[1] if req.image.startswith("data:") else req.image
    try:
        data = base64.b64decode(payload, validate=True)
    except binascii.Error:
        raise HTTPException(status_code=400, detail="Image is not valid base64.")
    return decode_image(data)

@app.post("/detect-components")
def detect_components(req: GenerateCircuitRequest) -> dict[str, Any]:
    from recognizer import RecognitionError, detect_boxes
    image = _decode_request_image(req)
    try:
        boxes = detect_boxes(image)
    except RecognitionError as e:
        raise HTTPException(status_code=422, detail=str(e))
    h, w = image.shape[:2]
    return {
        "image_width": w, "image_height": h,
        "detections": [{"type": b.cls_name, "conf": round(b.conf, 3), "bbox": {"x1": b.x1, "y1": b.y1, "x2": b.x2, "y2": b.y2}} for b in boxes],
    }

@app.post("/generate-circuit")
def generate_circuit(req: GenerateCircuitRequest) -> dict[str, Any]:
    from recognizer import RecognitionError, recognize
    image = _decode_request_image(req)
    try:
        return recognize(image, title=req.title)
    except RecognitionError as e:
        raise HTTPException(status_code=422, detail=str(e))

@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}